### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by YashGothi**

### CODE REVIEW

**Comment by pavlinaltd** [comment]
Hi Yash,
Hope you had a good weekend.
Do you have some time for  a shared screen?
I must figure out the website before emailing 4000 people.
Still not sure why some things are behaving as they are..At leats on my end..
Are you really familiar  with this script/?
I am really stressed for time now as the email should go out tomorrow..
Let me know.
Pav

From: Yash Gothi ***@***.***>
Date: Friday, December 27, 2024 at 03:35
To: pavlinaltd/MacedonianArtsCouncil-Website ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [pavlinaltd/MacedonianArtsCouncil-Website] Dev (PR #1)

Merged #1<https://github.com/pavlinaltd/MacedonianArtsCouncil-Website/pull/1> into main.

**Comment by YashGothi** [comment]
Hi Pavlina,
I hope you're doing well. Yes, I had made the changes to the MAC website,
but I reverted it back . So its now the same with the lady.

**Comment by pavlinaltd** [comment]
HI Yash,
  I know w you did not make the change,
I was thinking about some other issues.
Do you have time for a quick zoom now?
I just  got free.
Pavlina

From: Yash Gothi ***@***.***>
Date: Monday, December 30, 2024 at 12:53
To: pavlinaltd/MacedonianArtsCouncil-Website ***@***.***>
Cc: Pavlina ***@***.***>, Comment ***@***.***>
Subject: Re: [pavlinaltd/MacedonianArtsCouncil-Website] Dev (PR #1)
Hi Pavlina,
I hope you're doing well. Yes, I had made the changes to the MAC website,
but I reverted it back . So its now the same with the lady.

**Comment by YashGothi** [comment]
Yes

**Comment by pavlinaltd** [comment]
Ok I was on phone with doctor. Are you ok now??
P

From: Yash Gothi ***@***.***>
Date: Monday, December 30, 2024 at 16:10
To: pavlinaltd/MacedonianArtsCouncil-Website ***@***.***>
Cc: Pavlina ***@***.***>, Comment ***@***.***>
Subject: Re: [pavlinaltd/MacedonianArtsCouncil-Website] Dev (PR #1)
Yes

**Comment by YashGothi** [comment]
Yes, I can join

**Comment by pavlinaltd** [comment]
I am on.. and sent you the  link…


From: Yash Gothi ***@***.***>
Date: Monday, December 30, 2024 at 16:46
To: pavlinaltd/MacedonianArtsCouncil-Website ***@***.***>
Cc: Pavlina ***@***.***>, Comment ***@***.***>
Subject: Re: [pavlinaltd/MacedonianArtsCouncil-Website] Dev (PR #1)
Yes, I can join

**Pull request merged**
